owncloud/android-library

src/com/owncloud/android/lib/common/network/WebdavEntry.java
src/com/owncloud/android/lib/resources/files/RemoteFile.java

Adapt WebDav parser for receiving exponential values in QUOTAS

Fix refresh large default storage

---

src/com/owncloud/android/lib/common/accounts/AccountUtils.java

This code never worked as intended. Please consider adding unit tests.

Use .equals instead of !=

---

src/com/owncloud/android/lib/common/network/WebdavEntry.java
src/com/owncloud/android/lib/common/network/WebdavUtils.java
src/com/owncloud/android/lib/common/operations/RemoteOperationResult.java
src/com/owncloud/android/lib/common/utils/Log_OC.java
src/com/owncloud/android/lib/resources/files/ChunkedUploadRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/DownloadRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/UploadRemoteFileOperation.java

Minor changes to support synchronization of full folders in OC app

---

src/com/owncloud/android/lib/resources/shares/UpdateRemoteShareOperation.java
test_client/tests/src/com/owncloud/android/lib/test_project/test/UpdatePublicShareTest.java

Handle of the PUT parameter "publicUpload" from the API, and a new automated test of public shares.

Edit public share permission

---

src/com/owncloud/android/lib/common/network/ChunkFromFileChannelRequestEntity.java
src/com/owncloud/android/lib/common/network/FileRequestEntity.java
src/com/owncloud/android/lib/common/operations/RemoteOperation.java
src/com/owncloud/android/lib/common/operations/RemoteOperationResult.java
src/com/owncloud/android/lib/resources/files/UploadRemoteFileOperation.java
src/com/owncloud/android/lib/resources/status/OwnCloudVersion.java

@owncloud/android-developers
Forgot to create this PR too, bound to https://github.com/owncloud/android/pull/1493 . Feel free to review & comment.

Support for changes in https://github.com/owncloud/android/pull/1493

---

src/com/owncloud/android/lib/common/OwnCloudBasicCredentials.java
src/com/owncloud/android/lib/common/OwnCloudBearerCredentials.java
src/com/owncloud/android/lib/common/OwnCloudCredentials.java
src/com/owncloud/android/lib/common/OwnCloudCredentialsFactory.java
src/com/owncloud/android/lib/common/OwnCloudSamlSsoCredentials.java

Replication of PR #114 of @LukeOwncloud in official repo in order to have the right travis config to assure tests are passed.

Fix non alphanumeric chars in password

---

.travis.yml
AndroidManifest.xml
build.gradle
project.properties
sample_client/AndroidManifest.xml
sample_client/build.gradle
sample_client/project.properties
test_client/AndroidManifest.xml
test_client/build.gradle
test_client/project.properties
test_client/tests/project.properties

Changes for Android N

---

src/com/owncloud/android/lib/resources/users/GetRemoteUserQuotaOperation.java
src/com/owncloud/android/lib/resources/users/RemoteGetUserQuotaOperation.java
test_client/src/com/owncloud/android/lib/test_project/TestActivity.java
test_client/tests/src/com/owncloud/android/lib/test_project/test/GetUserQuotaTest.java

As a followup to to old PR https://github.com/owncloud/android-library/pull/44 new pull was made with fixes and comments from @davivel

User quota

---

sample_client/src/com/owncloud/android/lib/sampleclient/MainActivity.java
src/com/owncloud/android/lib/resources/files/ChunkedUploadRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/UploadRemoteFileOperation.java
test_client/src/com/owncloud/android/lib/test_project/TestActivity.java
test_client/tests/src/com/owncloud/android/lib/test_project/test/UploadFileTest.java

Fixes https://github.com/owncloud/android/issues/761

File modification date lost when uploading file

---

src/com/owncloud/android/lib/common/OwnCloudClient.java

Fixes https://github.com/owncloud/android/issues/1847#issuecomment-267558274

Fix crash with invalid TCP port

---

build.gradle
src/com/owncloud/android/lib/common/operations/RemoteOperationResult.java

Fix https://github.com/owncloud/android/issues/1722

Handle 503 code error

---

ant.properties
src/com/owncloud/android/lib/common/network/AdvancedSslSocketFactory.java
src/com/owncloud/android/lib/common/network/WriteTimeoutEnforcer.java
src/com/owncloud/android/lib/resources/files/DownloadRemoteFileOperation.java

Supplements https://github.com/owncloud/android/pull/1927

Improve support for unexpected loss of network connection.

---

src/com/owncloud/android/lib/common/network/WebdavEntry.java
src/com/owncloud/android/lib/common/network/WebdavUtils.java
src/com/owncloud/android/lib/resources/files/ReadRemoteFolderOperation.java
src/com/owncloud/android/lib/resources/files/RemoteFile.java

Do not merge before release 2.5.0 of app.

Add privatelink property support to processing of WebDAV responses

---

src/com/owncloud/android/lib/common/network/WebdavEntry.java

fixes https://github.com/owncloud/android/issues/2167

fix empty screen for guest users

---

build.gradle
sample_client/AndroidManifest.xml
sample_client/assets/oc_sample.txt
sample_client/res/layout/main.xml
sample_client/res/values/strings.xml
sample_client/src/com/owncloud/android/lib/sampleclient/MainActivity.java

Update the sample client app to perform some basic operations described in https://github.com/owncloud/android-library/issues/51 to test OkHttp with the new endpoint before starting the network library replacement.

Test OkHttp and new endpoint before network library replacement

---

src/com/owncloud/android/lib/resources/shares/CreateRemoteShareOperation.java
src/com/owncloud/android/lib/resources/shares/GetRemoteShareOperation.java
src/com/owncloud/android/lib/resources/shares/GetRemoteShareesOperation.java
src/com/owncloud/android/lib/resources/shares/GetRemoteSharesForFileOperation.java
src/com/owncloud/android/lib/resources/shares/GetRemoteSharesOperation.java
src/com/owncloud/android/lib/resources/shares/RemoveRemoteShareOperation.java
src/com/owncloud/android/lib/resources/shares/ShareToRemoteOperationResultParser.java
src/com/owncloud/android/lib/resources/shares/ShareUtils.java
src/com/owncloud/android/lib/resources/shares/ShareXMLParser.java
src/com/owncloud/android/lib/resources/shares/UpdateRemoteShareOperation.java
src/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.java
src/com/owncloud/android/lib/resources/users/GetRemoteUserInfoOperation.java

Fix https://github.com/owncloud/android/issues/2264
Needs https://github.com/owncloud/android/pull/2271

Show reshares

---

src/com/owncloud/android/lib/common/OwnCloudClient.java
src/com/owncloud/android/lib/common/utils/RandomUtils.java

Implements https://github.com/owncloud/android/issues/2055
It needs https://github.com/owncloud/android/pull/2314

Use UUID v4 to represent request ids and log it

---

build.gradle
src/com/owncloud/android/lib/resources/shares/GetRemoteShareOperation.java

Implements https://github.com/owncloud/android/issues/2322
Needs https://github.com/owncloud/android/pull/2323

Fix crash when creating public links

---

LICENSE.md
README.md
pom.xml

Implements #205
Needs https://github.com/owncloud/android/pull/2325

Delete jackrabbit dependencies and include OkHttp/Dav4Android ones

---

src/com/owncloud/android/lib/resources/files/UploadRemoteFileOperation.java

Fixes https://github.com/owncloud/android/issues/2304
Needs https://github.com/owncloud/android/issues/2306

Av. offline with jobs

---

src/com/owncloud/android/lib/common/operations/RemoteOperationResult.java

Fix corresponding to to [PR#2248](https://github.com/owncloud/android/pull/2248)

Changes for handling HTTP_METHOD_NOT_FOUND responses

---

src/com/owncloud/android/lib/resources/shares/CreateRemoteShareOperation.java

Needs https://github.com/owncloud/android/pull/2332

Release 0.9.21

---

src/com/owncloud/android/lib/common/OwnCloudClient.java
src/com/owncloud/android/lib/common/accounts/AccountUtils.java
src/com/owncloud/android/lib/resources/files/CopyRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/CreateRemoteFolderOperation.java
src/com/owncloud/android/lib/resources/files/DownloadRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/ExistenceCheckRemoteOperation.java
src/com/owncloud/android/lib/resources/files/MoveRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/ReadRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/ReadRemoteFolderOperation.java
src/com/owncloud/android/lib/resources/files/RemoteFile.java
src/com/owncloud/android/lib/resources/files/RemoveRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/RenameRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/UploadRemoteFileOperation.java
src/com/owncloud/android/lib/resources/files/chunks/ChunkedUploadRemoteFileOperation.java
src/com/owncloud/android/lib/resources/users/GetRemoteUserQuotaOperation.java

Fixes https://github.com/owncloud/android/issues/2338 via https://github.com/owncloud/android/issues/2340
Needs https://github.com/owncloud/android/pull/2341

Release 0.9.22

---

src/com/owncloud/android/lib/resources/files/RemoteFile.java

Fixes owncloud/android#2347 via owncloud/android#2354
Needs https://github.com/owncloud/android/pull/2354

Release 0.9.23

---

src/com/owncloud/android/lib/resources/files/RemoteFile.java

Fixes owncloud/android#2365 via https://github.com/owncloud/android/issues/2364
Needs https://github.com/owncloud/android/pull/2366

Release 0.9.24

---

src/com/owncloud/android/lib/resources/files/RemoteFile.java

It needs https://github.com/owncloud/android/pull/2370

Release 0.9.24 stable

---

build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java

btw, the complete repo needs a code formatter applied by `git checkout` out of the box. 
I will make such a PR later

apply some Lint fixes

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.java

Related to https://github.com/owncloud/android/issues/2228
Needs https://github.com/owncloud/android/pull/2455

Read enforced_for capability

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/GetRemoteShareesOperation.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/OCShare.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.java

Implements https://github.com/owncloud/android/issues/2284
Needed for https://github.com/owncloud/android/pull/2428

Include and parse shareWithAdditionalInfo to be used in shares autocompletion and list

---

build.gradle

see what's changed https://androidstudio.googleblog.com/2019/03/android-studio-332-available.html

Android Studio 3.3.2

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/OwnCloudBasicCredentials.java

Fixes https://github.com/owncloud/android/issues/2451
Needed for https://github.com/owncloud/android/pull/2542

Fix "Login fails with "§" in password "

---

build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/CreateRemoteShareOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/RemoteShare.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/UpdateRemoteShareOperation.kt

Implements https://github.com/owncloud/android/issues/2516
Needs https://github.com/owncloud/android/pull/2522

New arch/update public share for file

---

owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/AndroidManifest.xml

Needed for https://github.com/owncloud/android/pull/2553

[Release] 1.0.1 beta v1

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/RemoveRemoteShareOperation.kt

Implements https://github.com/owncloud/android/issues/2517
Needs https://github.com/owncloud/android/pull/2544

[New arch] Delete public share

---

owncloudComLibrary/build.gradle

Needed for https://github.com/owncloud/android/issues/2515

[Release] 1.0.1

---

owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/2621
Needed for https://github.com/owncloud/android/pull/2622

[Release] 1.0.2 beta 1

---

owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/2611
Needed for https://github.com/owncloud/android/pull/2629

[Release] 1.0.2

---

.classpath
.idea/codeStyles/Project.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/RemoteShare.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareToRemoteOperationResultParser.kt

Simply bring library up to date with 
* most recent stable Android Studio
* target to Android Q
* most recent stable Kotlin

Android Studio 3.5.0

---

owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/2645
Needed for https://github.com/owncloud/android/pull/2666

[Release] 1.0.3

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/RemoteCapability.kt

Implements https://github.com/owncloud/android/issues/2300
Needed for https://github.com/owncloud/android/pull/2678

Add min number of character to search capability

---

owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/OwnCloudVersion.kt

Implements https://github.com/owncloud/android/issues/2765
Needed for https://github.com/owncloud/android/pull/2766

Release 1.0.4.1

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFolderOperation.java

prevent a crash

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFile.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFileUtil.kt

Implements https://github.com/owncloud/android/issues/2822
Needed for https://github.com/owncloud/android/pull/2836

Support for usernames with character +

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

App PR: https://github.com/owncloud/android/pull/2831

Android Studio 3.6.2

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/WebdavUtils.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/FileService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/implementation/OCFileService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/ShareService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/ShareeService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/implementation/OCShareService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/implementation/OCShareeService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/services/CapabilityService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/services/ServerInfoService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/services/implementation/OCCapabilityService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/services/implementation/OCServerInfoService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/users/services/UserService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/users/services/implementation/OCUserService.kt

Implements:
- https://github.com/owncloud/android/issues/2808
- https://github.com/owncloud/android/issues/2794
Needed for https://github.com/owncloud/android/pull/2826

[New arch] Complete login

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/RemoteCapability.kt

Needed for https://github.com/owncloud/android/pull/2853

Remove search min length capability

---

build.gradle

App: https://github.com/owncloud/android/pull/2871

Update Android Studio to 3.6.3

---

owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/2813
Needed for https://github.com/owncloud/android/pull/2876

[Release] 1.0.5

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Needed for https://github.com/owncloud/android/pull/2889

Android Studio 4.0

---

owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpClient.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/TLSSocketFactory.java
sample_client/build.gradle

Implements: https://github.com/owncloud/android/issues/2576
Needed for: https://github.com/owncloud/android/pull/2897

Upgrade target version to v29

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/FileUtils.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFile.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RenameRemoteFileOperation.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/chunks/ChunkedUploadRemoteFileOperation.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/RemoteShare.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/users/GetRemoteUserAvatarOperation.kt
sample_client/src/main/java/com/owncloud/android/lib/sampleclient/MainActivity.java

It's related to https://github.com/owncloud/android/pull/2907

Use Android separator instead of homemade one

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/SingleSessionManager.java

Fixes https://github.com/owncloud/android/issues/2906
Needed for https://github.com/owncloud/android/pull/2912

[Fix] Refresh credentials

---

README.md
owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/OwnCloudBasicCredentials.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/DavMethod.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/DavUtils.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/PropfindMethod.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/PutMethod.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CheckPathExistenceRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFolderOperation.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFile.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFileUtil.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/users/GetRemoteUserQuotaOperation.kt

Update network library and readme with last changes.
Implements
Lib: #280
App: https://github.com/owncloud/android/issues/2862
Needed for: https://github.com/owncloud/android/pull/2904

Use the latest changes of dav4jvm (Okhttp 4.6.0)

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/OwnCloudVersion.kt

Implements https://github.com/owncloud/android/issues/2915
Needed for https://github.com/owncloud/android/pull/2917

Add support for version.hide config

---

build.gradle

Needed for: https://github.com/owncloud/android/pull/2925

Android Studio 4.0.1

---

owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/2945
Needed for https://github.com/owncloud/android/pull/2949

[Release] 1.0.7

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java

Removing a legacy cookie header

Remove single cookie header

---

owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/2963
Needed for https://github.com/owncloud/android/pull/2979

[Release] 1.0.8

---

owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java

Merge 1.0.8 into stable branch
App: https://github.com/owncloud/android/pull/2982

1.0.8 stable

---

build.gradle
owncloudComLibrary/build.gradle

Update Android Studio version to 4.1, kotlin to 1.4.10 and perform a little cleanup.
Needed for https://github.com/owncloud/android/pull/2975

Update dependencies and perform a little cleanup

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/SingleSessionManager.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperation.java

This will resolve cookie persistence which should solve braking the cookiejar after restarting the app.
App PR: https://github.com/owncloud/android/pull/3002

Remove cookie persistence

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/GetRemoteShareOperation.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/RemoteShare.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/RemoveRemoteShareOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/UpdateRemoteShareOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/ShareService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/implementation/OCShareService.kt

Implements: https://github.com/owncloud/android/issues/2985
Needed for:https://github.com/owncloud/android/pull/3011

Parse shareId as String

---

owncloudComLibrary/build.gradle

Implements: https://github.com/owncloud/android/issues/2883
Needed for: https://github.com/owncloud/android/pull/3020

Move appauth dependency to ownCloudApp

---

build.gradle
owncloudComLibrary/build.gradle

Update kotlin plugin to 1.4.20
App: https://github.com/owncloud/android/pull/3027

Android Studio 4.1.1

---

owncloudComLibrary/build.gradle

It updates logcat content during observation

Show logcat live

---

owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/2993
Needed for https://github.com/owncloud/android/pull/3053

[Release] 1.0.9

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/OwnCloudCredentialsFactory.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/GetOIDCDiscoveryRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/TokenRequestRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/params/TokenRequestParams.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/responses/OIDCDiscoveryResponse.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/responses/TokenResponse.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/services/OIDCService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/services/implementation/OCOIDCService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/services/ServerInfoService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/services/implementation/OCServerInfoService.kt

Implements https://github.com/owncloud/android/issues/3038
Needed for https://github.com/owncloud/android/pull/3043

[Feature] OAuth2 - OIDC Custom implementation

---

build.gradle

Bump kotlinVersion from 1.4.21 to 1.4.30

Bump kotlinVersion from 1.4.21 to 1.4.30

---

owncloudComLibrary/build.gradle

Update versionName and versionCode for a new beta
Needed for https://github.com/owncloud/android/pull/3140

[RELEASE] 1.0.10-beta.1

---

owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteStatusOperation.kt

Implements https://github.com/owncloud/android/issues/3098
Needed for https://github.com/owncloud/android/pull/3149

[Release] 1.0.10

---

build.gradle

App: https://github.com/owncloud/android/pull/3161

Bump gradle version to 1.4.3

---

build.gradle

App: https://github.com/owncloud/android/pull/3191

Bump kotlin version

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/StatusRequester.kt

App: https://github.com/owncloud/android/pull/3165

Fix some ktlint findings

---

.editorconfig
build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/services/implementation/OCCapabilityService.kt
owncloudComLibrary/src/test/java/com/owncloud/android/lib/resources/shares/responses/ShareeResponseTest.kt

It's smarter to check library separately.
When this one is merged, we could use this `.editorconfig` in app as well, to have only one settings file
Don't forget to add `./gradlew ktLintCheck` in CI

ktLint check in library

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/chunks/ChunkedUploadRemoteFileOperation.java

Fix xodo sync bug.
Issue: https://github.com/owncloud/android/issues/2752
App PR: https://github.com/owncloud/android/pull/3220

fix xodo sync bug

---

owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java

Implements https://github.com/owncloud/android/issues/3197
Needed for: https://github.com/owncloud/android/pull/3243

[Release] 1.0.11

---

build.gradle

Bump kotlin and gradle version
Needed for: https://github.com/owncloud/android/pull/3263

Bump kotlin version and AS

---

build.gradle

Bump kotlin and kotlin gradle plugin

Bump kotlin to 1.5.20

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/params/TokenRequestParams.kt

Add a new parameter to support PKCE
Needed for https://github.com/owncloud/android/pull/3310

Add PKCE support

---

owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/3282
Needed for https://github.com/owncloud/android/pull/3312

[Release] 1.0.12

---

owncloudComLibrary/build.gradle

Update versionName and versionCode preparing for a new beta: https://github.com/owncloud/android/issues/3397
App pr: https://github.com/owncloud/android/pull/3433

[Release] 1.0.13-beta.1

---

owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/LoggingHelper.kt

Updating the library for a new release: https://github.com/owncloud/android/issues/3325

[Release] 1.0.13

---

build.gradle

Bump Kotlin version to 1.5.31

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Bump gradle version to 7.3

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/RemoteCapability.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/responses/CapabilityResponse.kt

Implements: https://github.com/owncloud/android/issues/3285
App: https://github.com/owncloud/android/pull/3438

[Feature] Respect capability for Avatar support

---

build.gradle

Kotlin 1.6.10 -> https://github.com/JetBrains/kotlin/releases/tag/v1.6.0
App: https://github.com/owncloud/android/pull/3483

Bump kotlin version to 1.6.10

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/LogBuilder.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.kt

It's about to fix these three lint warnings

Fix lint warnings

---

owncloudComLibrary/build.gradle

Updating the library for a new release: https://github.com/owncloud/android/issues/3497
App: https://github.com/owncloud/android/pull/3551

[Release] 1.0.14

---

build.gradle
owncloudComLibrary/build.gradle

Bump gradle and kotlin versions to the latest ones.
BTW, bump the target sdk to 31.
App: https://github.com/owncloud/android/pull/3614

Bump gradle and kotlin to the latest versions

---

build.gradle

App: https://github.com/owncloud/android/pull/3664
Superseeds #480

Bump kotlin version to 1.6.21

---

owncloudComLibrary/build.gradle

Update versionName and versionCode preparing for a new beta: https://github.com/owncloud/android/issues/3597
App pr: https://github.com/owncloud/android/pull/3670

[Release] 1.0.15-beta.1

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/RemoteCapability.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/responses/CapabilityResponse.kt

Implements https://github.com/owncloud/android/issues/3732
Needed for https://github.com/owncloud/android/pull/3738

[Feature] Respect private link capability

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/GetUrlToOpenInWebRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/FileService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/implementation/OCFileService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/RemoteCapability.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/responses/CapabilityResponse.kt

Implements https://github.com/owncloud/android/issues/3672

[Feature] Open in web

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java

Cleaning up the owncloud version from the owncloud client since it was not used anywhere.
Related to https://github.com/owncloud/android/pull/3765

[New arch] Clean legacy classes

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java

Issue: https://github.com/owncloud/android/issues/3781
App PR: https://github.com/owncloud/android/pull/3784

Handle 425 when trying to open in web

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFile.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFileUtil.kt

Handle 425 TOO EARLY propfind responses

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/CommonOcsResponse.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/GetRemoteShareesOperation.kt
owncloudComLibrary/src/test/java/com/owncloud/android/lib/resources/shares/responses/ShareeResponseTest.kt

Fixes https://github.com/owncloud/android/issues/3724#issuecomment-1307116456

[New arch] Data field not mandatory on ocs responses

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/AndroidManifest.xml
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/services/implementation/OCCapabilityService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/services/implementation/OCServerInfoService.kt

Bump several dependencies to latest versions.
Added namespace, still need to check how it affects oB
App PR: https://github.com/owncloud/android/pull/3810

Bump several dependencies at the same time

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/ConnectionValidator.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java

Added several logs to debug potential errors when receiving an unauthorized exception

Add several logs to try to debug potential errors related to token refreshment

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/RemoteCapability.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/responses/CapabilityResponse.kt

Issue: https://github.com/owncloud/android/issues/3803
App PR: https://github.com/owncloud/android/pull/3842

[SPACES] Save account type and display new tab for spaces

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/GetRemoteSpacesOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/responses/SpacesResponse.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/services/OCSpacesService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/services/SpacesService.kt

Issue: https://github.com/owncloud/android/issues/3805
App PR: https://github.com/owncloud/android/pull/3843

[SPACES] Create new "Spaces" view

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/responses/SpacesResponse.kt

Shares space does have some nullable fields like `owner`
Mountpoints do not have `lastModifiedDateTime` and eTag is on the `remoteItem` node. `remoteItem` not parsed yet, will be done in the future
App PR: https://github.com/owncloud/android/pull/3856
```
{
"value": [
{
"driveAlias": "virtual/shares",
"driveType": "virtual",
"id": "a0ca6a90-a365-4782-871e-d4444$a0ca6a90-a365-4782-871e-d4444",
"lastModifiedDateTime": "2023-01-11T17:03:47.139082173Z",
"name": "Shares",
"quota": {
"remaining": 0,
"state": "exceeded",
"total": 0,
"used": 0
},
"root": {
"eTag": "\"695b26758d54a156771775099037adfb\"",
"id": "a0ca6a90-a365-4782-871e-d4444$a0ca6a90-a365-4782-871e-d4444",
"webDavUrl": "server/dav/spaces/a0ca6a90-a365-4782-871e-d4444$a0ca6a90-a365-4782-871e-d4444"
},
"webUrl": …
```

[Spaces] Fix shares space parsing

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/SingleSessionManager.java

Issue: https://github.com/owncloud/android/issues/3870
App PR: https://github.com/owncloud/android/pull/3871
Potential fix to the error after logging in

[Release] 2.0.2

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CreateRemoteFolderOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFileOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFolderOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFile.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoveRemoteFileOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RenameRemoteFileOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/chunks/RemoveRemoteChunksFolderOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/FileService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/implementation/OCFileService.kt
owncloudComLibrary/src/test/java/com/owncloud/android/lib/RemoteFileTest.kt

App: https://github.com/owncloud/android/issues/3807
App PR: https://github.com/owncloud/android/pull/3861

[SPACES] List&Browse Spaces content

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/DownloadRemoteFileOperation.kt

Implements https://github.com/owncloud/android/issues/3808
App PR: https://github.com/owncloud/android/pull/3891

[Spaces] Local Storage

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CheckPathExistenceRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/UploadFileFromFileSystemOperation.kt

App: https://github.com/owncloud/android/issues/3879
App PR: https://github.com/owncloud/android/pull/3913

[SPACES] Upload content to spaces

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/LogInterceptor.kt

Improved some HTTP logs. Now, it shows also the URL on the HTTP response to help debugging
App PR: https://github.com/owncloud/android/pull/3952

[Release] 2.0.3

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/webfinger/GetInstancesViaWebfingerOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/webfinger/responses/WebfingerResponse.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/webfinger/services/WebfingerService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/webfinger/services/implementation/OCWebfingerService.kt
owncloudComLibrary/src/test/java/com/owncloud/android/lib/resources/webfinger/responses/WebfingerResponseTest.kt

Implements https://github.com/owncloud/android/issues/3943
App PR: https://github.com/owncloud/android/pull/3945

Authenticated WebFinger

---

build.gradle
owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/3900
App PR https://github.com/owncloud/android/pull/3957

[Technical] Replace kapt with ksp

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/DavUtils.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CheckPathExistenceRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/GetBaseUrlRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFileOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFolderOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFile.kt

App: https://github.com/owncloud/android/issues/3934
App PR: https://github.com/owncloud/android/pull/3960

[Release] 2.1 beta.1

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java

App: https://github.com/owncloud/android/issues/3980

Add accept language header to all requests

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/GetRemoteAppRegistryOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/GetUrlToOpenInWebRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/responses/AppRegistryResponse.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/services/AppRegistryService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/services/OCAppRegistryService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/FileService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/implementation/OCFileService.kt

Implements https://github.com/owncloud/android/issues/3860
App PR: https://github.com/owncloud/android/pull/3990

[Feature] Open in specific web provider

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java

App: https://github.com/owncloud/android/issues/3948
App PR: https://github.com/owncloud/android/pull/4013

[FIX] Introduce new error message for ProtocolException

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/CreateRemoteFileWithAppProviderOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/GetUrlToOpenInWebRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/services/AppRegistryService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/services/OCAppRegistryService.kt

Implements https://github.com/owncloud/android/issues/3995
App PR: https://github.com/owncloud/android/pull/4023

[FEATURE REQUEST] Create new file via Open in Web

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/CreateRemoteShareOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/UpdateRemoteShareOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/ShareService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/implementation/OCShareService.kt

App: https://github.com/owncloud/android/issues/4012

[Release] 2.1

---

README.md
owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/AndroidManifest.xml

App: https://github.com/owncloud/android/issues/3245

[TECHNICAL] Upgrade min SDK to Android 6 (v23)

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/CopyMethod.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/MoveMethod.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CopyRemoteFileOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/MoveRemoteFileOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/FileService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/implementation/OCFileService.kt

App: https://github.com/owncloud/android/issues/3935

[FEATURE REQUEST] Copy/move conflict solved by users

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/GetRemoteAppRegistryOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/services/AppRegistryService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/services/OCAppRegistryService.kt

App: https://github.com/owncloud/android/issues/4075

[FEATURE REQUEST] Respect app_provider values from capabilities
