owncloud/android-library

src/com/owncloud/android/lib/common/utils/Log_OC.java

I don't quite get the reason for `mBuf` here as in `com.owncloud.android.lib.common.utils.Log_OC#appendLog` anyways a new `BufferedWriter` is started but it might make sense to close this here as this will otherwise cause warnings in static code scanners.
Didn't test this as I don't have a Android device and so it requires extensive testing.

Close resource in finally block

---

build.gradle

With the new Android Studio 2.1 an new version of the android gradle plugin was made available v2.1.0

Update gradle android plugin to 2.1.0

---

src/com/owncloud/android/lib/resources/users/GetRemoteUserInfoOperation.java

Fixes wrong path to UserInfo resource that was taking advantage of extra "intelligence" in server version to redirect paths, dropped with OC server 10.

Update entry point to get user info

---

.travis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
sample_client/build.gradle
test_client/build.gradle

To be in line with recommendations of Android Studio 2.3.1, current stable version of the IDE.

Update version of build tools and gradle dependencies

---

.travis.yml
build.gradle
sample_client/build.gradle
test_client/build.gradle
test_client/tests/build.gradle

Dependencies to update:
- Update locally via SDK Manager and select version to use in build.gradle: `buildToolsVersion '26.0.2'`
- .travis.yml: `- build-tools-26.0.2`
- Update locally via SDK Manager to 26.0.1
- .travis.yml: `- platform-tools`
- Update locally via SDK Manager to 26.1.1
- .travis.yml: ~~`- tools` and `yes | - sdkmanager --verbose tools` (not updating properly, travis first install tools 25.2.5 and replace it with 25.2.3 version)~~ Fixed by using the new sdkmanager to install all the Android SDK dependencies and deleting the android components section.

[WIP] Update Android tools

---

src/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.java

Fix for https://github.com/owncloud/android/issues/2078 . 
Summary: If files_versioning app is disabled, server capabilities response does not include any information about versioning. Trying to access undefined index is leading to an error in "GetRemoteCapabilitiesOperation" and client cannot determine server version. To fix the problem, I added "has" check for "PROPERTY_VERSIONING".

check for PROPERTY_VERSIONING is exist when learning capabilities

---

src/com/owncloud/android/lib/common/OwnCloudClient.java

For logging it was used a separate OC_X_REQUEST_ID and makes the logging complete wrong
Btw , currently I see no sense to set this OC_X_REQUEST_ID at all

fix a bug with wrong used OC_X_REQUEST_ID

---

AndroidManifest.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
sample_client/AndroidManifest.xml
sample_client/build.gradle

Needs https://github.com/owncloud/android/pull/2324

Android Studio 3.2.1

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/Log_OC.java

It needs https://github.com/owncloud/android/pull/2415
time and text in same line, no empty lines
```
2018/12/19 08:06:49
GetRemoteSharesForFileOperation : Got 1 shares
2018/12/19 08:06:49
FileDataStorageManager : Sending 16 operations to FileContentProvider
2018/12/19 08:06:49
FileContentProvider : applying batch in provider com.owncloud.android.providers.FileContentProvider@4402c7c (temporary: false)
2018/12/19 08:06:49
FileContentProvider : applied batch in provider com.owncloud.android.providers.FileContentProvider@4402c7c
2018/12/19 08:06:49
RefreshFolderOperation : Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
```
```
2018/12/19 08:46:38 FileDisplayActivity : onResume() starting
2018/12/19 08:46:38 OCFileListFragment : …
```

compact logfile

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/Log_OC.java

this is a pre-task to colorize log output and add ability to filter on loglevel

add log level to output

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpClient.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/TLSSocketFactory.java

Implements:
- Include TLSv1.2 support and make it work on 19 devices: https://github.com/owncloud/android-library/pull/238
Needs https://github.com/owncloud/android/pull/2472
**IMPORTANT**: tag `1.0.0_oem` in this branch

Release 1.0.0 oem

---

owncloudComLibrary/build.gradle

`compileSdkVersion` was upgraded to 29 via https://github.com/owncloud/android-library/pull/266 but this is something we usually do through specific issues like https://github.com/owncloud/android/issues/2576 , so let's rever this scenario and delay the upgrade for later

Revert compileSdkVersion to 28

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudAccount.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClientManager.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClientManagerFactory.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/SingleSessionManager.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/oauth/BearerCredentials.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/AdvancedX509TrustManager.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/ProgressiveDataTransferer.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/users/GetRemoteUserAvatarOperation.java

Inspired by conflicted and non-maintained https://github.com/owncloud/android-library/pull/186 I did same with this PR, to be able to close https://github.com/owncloud/android-library/pull/186 when this is done

code cleanup

---

owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/Log_OC.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/LoggingHelper.kt

It's the requested PR on your repo instead of https://github.com/owncloud/android-library/pull/275
Requested here https://github.com/owncloud/android/pull/2725#issuecomment-555971894
Implements https://github.com/owncloud/android/issues/2730
Needed for https://github.com/owncloud/android/pull/2725

Better logging (on upstream)

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/RemoteCapability.kt

Implements https://github.com/owncloud/android/issues/2701
Needed for https://github.com/owncloud/android/pull/2728

[New arch] [Modularization] Tests and cleanup

---

owncloudComLibrary/build.gradle

Implements https://github.com/owncloud/android/issues/2727
Needed for https://github.com/owncloud/android/pull/2758

[Release] 1.0.4

---

owncloudComLibrary/build.gradle
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpClient.java

Implements https://github.com/owncloud/android/issues/2738
Needed for https://github.com/owncloud/android/pull/2748

Get rid of Android 4.4 support

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/ChunkFromFileRequestBody.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/FileRequestBody.java

(cherry picked from commit 53a8ce122c7f0d4ef6d47e76a29b15fc68197135)
Implements https://github.com/owncloud/android/issues/2743
It needs https://github.com/owncloud/android/pull/2764

Reduce logging in ChunkFromFileRequestBody

---

sample_client/build.gradle

Your Bitrise is a black box and I don't know what you test. 
But I know, you don't run
` ./gradlew clean build`
otherwise you will see
Needed for: https://github.com/owncloud/android/pull/2768

Finish remove Android 4.4 support

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperation.java

fix a typo and some lint warnings

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/FileUtils.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFile.java

Fixes a problem where file size was 0 due to hardcoded mimetypes.
Needed for https://github.com/owncloud/android/pull/3040
oc10 -> "DIR"
ocis -> "httpd/unix-directory"

Use constants instead of hardcoded values for dir mimetypes

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/RegisterClientRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/params/ClientRegistrationParams.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/params/TokenRequestParams.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/responses/ClientRegistrationResponse.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/services/implementation/OCOIDCService.kt

Implements https://github.com/owncloud/android/issues/3054
Needed for https://github.com/owncloud/android/pull/3073

[FEATURE] OIDC Dynamic Client Registration

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/responses/OIDCDiscoveryResponse.kt

`registration_endpoint` is mandatory at the moment but it should not according to https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata
It should fix a problem that happens when `registration_endpoint` is not retrieved in the discovery.
App: https://github.com/owncloud/android/pull/3202

Make some fields not mandatory in discovery response

---

build.gradle

Replacing JCenter with MavenCentral.
Implements https://github.com/owncloud/android/issues/3084

MavenCentral

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/UploadFileFromContentUriOperation.kt

Implements: https://github.com/owncloud/android/issues/2899
Needed for https://github.com/owncloud/android/pull/3293
Added a new operation to upload files using the content Uri

[New arch] Camera Uploads

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/DownloadRemoteFileOperation.java

fix for issue: https://github.com/owncloud/android-library/issues/424

add error log when content-length not equal to transfaired bytes

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/HttpBaseMethod.kt

Fix https://github.com/owncloud/android/issues/3647
``` Create RemoteOperationResult from exception.
Message: IOException: unexpected end of stream on ...
Stacktrace: java.io.IOException: unexpected end of stream on...
at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:54)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
at com.owncloud.android.lib.common.http.LogInterceptor.intercept(LogInterc …
```

Fix unexpected end of stream when connecting with server

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/properties/OCShareTypes.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/properties/ShareTypeListProperty.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFolderOperation.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteFile.java

Add a new property to the propfind. So that, we can get if the file is shared directly in just one request.
App: https://github.com/owncloud/android/pull/3711

Retrieve share type directly within the propfind

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/chunks/ChunkedUploadFromFileSystemOperation.kt

When doing a manual content URI upload, now files are copied to local storage before uploading them.
App PR: https://github.com/owncloud/android/pull/3763

[New arch] Chunking bugfixing

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/RemoveRemoteShareOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/ShareService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/services/implementation/OCShareService.kt

There is no need to parse the response anymore. The app is not using that data, just checks if it was successful or not.
oC10 returned an empty list
oCIS returns an object
That's why it was not working properly on oCIS

Unsharing wont return anything anymore since result object was not used

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CheckPathExistenceRemoteOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CopyRemoteFileOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/MoveRemoteFileOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/FileService.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/implementation/OCFileService.kt

App: https://github.com/owncloud/android/issues/3863
App PR: https://github.com/owncloud/android/pull/3887

[SPACES] Copy and move operations

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
owncloudComLibrary/build.gradle

Bump kotlin version to 1.8.10 
Release details: https://kotlinlang.org/docs/whatsnew18.html#ide-support
`kotlin-stdlib-jdk7` and `kotlin-stdlib-jdk8`  have been merged into `kotlin-stdlib`
App PR: https://github.com/owncloud/android/pull/3911

Bump kotlin version to 1.8.10

---

owncloudComLibrary/build.gradle

Bump target sdk to 33, nothing relevant at library side
App: https://github.com/owncloud/android/pull/3972

[TECHNICAL] Bump target sdk to 33

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/responses/SpacesResponse.kt

Permissions will be handled via WebDav. So no need to maintain this parsing.

Remove permission parsing from spaces. 

---

owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/webfinger/GetInstancesViaWebFingerOperation.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/webfinger/responses/WebFingerResponse.kt
owncloudComLibrary/src/test/java/com/owncloud/android/lib/resources/webfinger/responses/WebFingerResponseTest.kt

Implementation https://github.com/owncloud/android/issues/3998
WebFinger call won't follow redirections. In case the lookup server is not directly accessible, we will continue the authentication flow with the regular `status.php` and `/remote.php/dav/files/`

Update WebFinger flow
